spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoder=utf-8&useSSL=true&serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
