spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:33306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9090

parameter:
  randomInt: ${random.int}
  randomString: ${random.value}

  school: 浙大城市学院
  class: 计算机 2004
